Feature/add login screen
nilsonsasaki/Aegro-Academy-Mobile pull request #1
Opened 2022-05-25 14:15 UTC by nilsonsasaki

it adds LoginScreen and makes it the homeScreen

2022-05-25 15:08 UTC, jhenriquedsilva approved these changes

2022-05-25 15:51 UTC, paulocenriquep requested changes
Boa tarde, Nilson! De acordo com o modelo de classe _User_, não haverá senha para o usuário. Apenas email.

2022-05-26 12:10 UTC, pauloHenrique-aegro approved these changes

2022-05-26 12:12 UTC, jhenriquedsilva approved these changes

2022-05-26 12:14 UTC, merged